name: pandora_json_api_decrypter
description: A tool to decrypt Pandora JSON API request and responses.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  iapetus:
    git:
      url: 'git://github.com/EpimetheusMusicPlayer/Iapetus.git'
      ref: '6a4a7e0cda84895765b970c3f90f13bbec2d97c4'

dev_dependencies:
  lint: ^1.5.3

flutter:
  uses-material-design: true