name: pandora_json_api_decrypter
description: A tool to decrypt Pandora JSON API request and responses.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  iapetus:
    git:
      url: 'https://github.com/EpimetheusMusicPlayer/iapetus.git'
      ref: 'a978d5c161481a8103fafcb0728dcaef5aa90c9f'

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true